thespoon-with-activerecord/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :restaurants

  # get 'restaurants', to: 'restaurants#index'
  # get 'restaurants/:id', to: 'restaurants#show'
  # get 'restaurants/new', to: 'restaurants#new'
  # post 'restaurants', to: 'restaurants#create'

  # get 'restaurants/:id/edit', to: 'restaurants#edit'
  # patch 'restaurants/:id', to: 'restaurants#update'

  # delete 'restaurants/:id', to: 'restaurants#destroy'

end

thespoon-with-activerecord/app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

thespoon-with-activerecord/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end
  def show
  end
  def new
    @restaurant = Restaurant.new
  end
  def create
    Restaurant.create(restaurant_params)
    redirect_to restaurants_path

  end
  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end
  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :stars)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

thespoon-with-activerecord/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%= stylesheet_link_tag
    'application', media: 'all', 'data-turbolinks-track': 'reload' %> <%=
    javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

thespoon-with-activerecord/app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.submit %>
<% end %>

thespoon-with-activerecord/app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

thespoon-with-activerecord/app/views/restaurants/index.html.erb
<h1>all restaurants</h1>
<% @restaurants.each do |restaurant| %>
<h2>
  <%= restaurant.name %>
</h2>
<p>
  <%= restaurant.address %>
</p>
<%= link_to restaurant.name, restaurant_path(restaurant) %>
<%= link_to  "delete", restaurant_path(restaurant), method: :delete %>
<% end %>

thespoon-with-activerecord/app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

thespoon-with-activerecord/app/views/restaurants/show.html.erb
<h1>restaurant</h1>
<%= @restaurant.name %>
<%= link_to "home", restaurants_path %>